### ISSUE TITLE
LanguageConfig

### ISSUE THREAD

**Issue by ImustnotfeaR** [crucialfelix/atom-supercollider#29]
Hi hi again, does the LanguageConfig class work in atom? I am trying to include some classes with the .addIIncludePath() & .store() methods which compile but after recompiling the library these paths aren't added.

**Comment by crucialfelix** [comment]
I'm actually fixing that right now.  I've got the brand new quarks system
working and it adds packages to language config.

with supercollider-js / atom I set it up to allow an easier config file,
but admitedly it isn't clean and simple enough. so I'm changing it now.

docs are here:
http://supercolliderjs.readthedocs.org/en/latest/configuration.html
https://github.com/crucialfelix/atom-supercollider

but basically create a .supercollider.yaml and add the includePaths there:

includePaths:

  /path/here

  /path/two

this will be made better and clearer soon. I will probably just parse
the lang config file so that by default it works exactly as normal sc
does.

but I want to enable having a project specific config file with
project specific quarks.

**Comment by ImustnotfeaR** [comment]
Ah yeah sweet.

Awesome work man, wish I knew more so i could help you out ! still pretty new programmer :)

**Comment by ImustnotfeaR** [comment]
nice that you can keep it in the project folder, is their an efficient way to have multiple projects with different yaml files ?

**Comment by crucialfelix** [comment]
you can do that right now. it just searches for the nearest yaml file and
uses that. so each project can have its own. keep your default one in your
home directory

now I want to include quarks in that system. so you can work on a project
and specify what quarks you want and when you run that project you get just
those quarks. also they are fixed forever so if you come back years later
they will use the same code and won't break.

but supercollider itself changes, so something will probably break :(

**Comment by ImustnotfeaR** [comment]
ace, thats way better than using LanguageConfig. Really cool idea.

**Comment by crucialfelix** [comment]
You can now use the normal LanguageConfig and it will honor those. 

You can also use the new Quarks system which uses the LanguageConfig to add includePaths.
(latest supercollider development version - you would need to pull and rebuild that)

You can load and save sets of includePaths using Quarks.load / Quarks.save or with the gui.
