### ISSUE TITLE
Quarks not recognised in Atom environment

### ISSUE THREAD

**Issue by LFSaw** [crucialfelix/atom-supercollider#34]
Hello,

just looked at atom-supercollider again, gets better and better, and I'll eventually very sure to use it as my regular IDE soon  :)
One thing I now noticed is that Quarks (from the git system) are not recognised, although I download them _through atom-sc_ via ```Quarks.gui```. Even after a restart, they are not visible...

**Comment by crucialfelix** [comment]
are you on the latest sc from master ?

there was a change a few weeks ago.

I'll check when I get a chance. you might be right and I forgot to change
the atom side.

**Comment by caseyanderson** [comment]
Quarks.gui; works for me in Atom. I cannot remember if I simply had to update or actually had to update the Quarks location after it moved. I can check later tonight when I am home from work, if that is helpful.

**Comment by LFSaw** [comment]
Yep, "latest" (a day old?) ...


thanks!
	Till

**Comment by bagong** [comment]
It might be easier to test Windows with Atom, as the showstopper bug seems to be a Qt issue...

**Comment by crucialfelix** [comment]
that would be interesting. let me know.

**Comment by crucialfelix** [comment]
Finally got a chance to fix this. Sorry for the delay.

Its a bit snakey: supercolliderjs dynamically creates a config file. Right now its mainly just to override the Error handling reportError methods.

But it also supports a local .supercollider.yaml file so you can have simple dependency management for each project you are working on.  http://supercolliderjs.readthedocs.org/en/latest/configuration.html#supercollider-yaml-and-sclang-config-yaml 

If you want to handle your dependencies that way (even I am not doing it yet) then you wouldn't use Quarks.gui

So anyway I had to override some methods in Quarks so that it would save to both the generated config and your original config (sclang_conf.yaml).  It was just writing to the dynamically generated config and that's why they weren't sticking.

One caveat: if you click the nice green Recompile Library button then supercollider-js does not notice and fails to re-install its interpreter helpers. So use shift-cmd-K to recompile from atom instead of using the button in sc gui.  Filing a separate bug for that.

**Comment by crucialfelix** [comment]
btw. Atom has gotten much faster recently and the new One themes are imho really nice.
